version: '2.2' # extends only support in 2.x


##########################################
# celery worker
##########################################


services:

  #################### celery base ##############################


  # celery beat：
  scheduler: &scheduler
    build:
      context: .
      dockerfile: docker/web/Dockerfile_celery
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DJANGO_SECRET_KEY=aHdCBMHXuxIxEhfRGFRp7Cp3N9CqEZEEAvwZVlBCazKExkEnzvVs4bYWC8Qqh9lg
      - SECRET_KEY=aHdCBMHXuxIxEhfRGFRp7Cp3N9CqEZEEAvwZVlBCazKExkEnzvVs4bYWC8Qqh9lg
      - DATABASE_URL=psql://postgres:postgres@db:5432/postgres
#    depends_on:
#      - db
#      - redis
    command: celery -A safe_transaction_service.taskapp.celery_app beat -S django_celery_beat.schedulers:DatabaseScheduler --loglevel INFO
    # command: celery -A safe_transaction_service.taskapp.celery_app worker --loglevel INFO --pool=gevent --autoscale=120,80


  #################### celery worker group ##############################

  # celery worker：
  celery_worker_default:
    <<: *scheduler
    container_name: celery_worker_default
    command: celery -A safe_transaction_service.taskapp.celery_app worker --loglevel INFO --pool=gevent --autoscale=120,80 -Q default

  celery_worker_contracts:
    <<: *scheduler
    container_name: celery_worker_contracts
    command: celery -A safe_transaction_service.taskapp.celery_app worker --loglevel INFO --pool=gevent --autoscale=120,80 -Q contracts

  celery_worker_notifications:
    <<: *scheduler
    container_name: celery_worker_notifications
    command: celery -A safe_transaction_service.taskapp.celery_app worker --loglevel INFO --pool=gevent --autoscale=120,80 -Q notifications

  celery_worker_tokens:
    <<: *scheduler
    container_name: celery_worker_tokens
    command: celery -A safe_transaction_service.taskapp.celery_app worker --loglevel INFO --pool=gevent --autoscale=120,80 -Q tokens

  ####################################################################################################

  celery_worker_history_index_new_proxies_task:
    <<: *scheduler
    command: celery -A safe_transaction_service.taskapp.celery_app worker --loglevel INFO --pool=gevent --autoscale=120,80 -Q history_index_new_proxies_task

  celery_worker_history_index_internal_txs_task:
    <<: *scheduler
    command: celery -A safe_transaction_service.taskapp.celery_app worker --loglevel INFO --pool=gevent --autoscale=120,80 -Q history_index_internal_txs_task

  celery_worker_history_index_safe_events_task:
    <<: *scheduler
    command: celery -A safe_transaction_service.taskapp.celery_app worker --loglevel INFO --pool=gevent --autoscale=120,80 -Q history_index_safe_events_task

  celery_worker_history_index_erc20_events_task:
    <<: *scheduler
    command: celery -A safe_transaction_service.taskapp.celery_app worker --loglevel INFO --pool=gevent --autoscale=120,80 -Q history_index_erc20_events_task

  celery_worker_history_process_decoded_internal_txs_task:
    <<: *scheduler
    command: celery -A safe_transaction_service.taskapp.celery_app worker --loglevel INFO --pool=gevent --autoscale=120,80 -Q history_process_decoded_internal_txs_task

  celery_worker_history_process_decoded_internal_txs_for_safe_task:
    <<: *scheduler
    command: celery -A safe_transaction_service.taskapp.celery_app worker --loglevel INFO --pool=gevent --autoscale=120,80 -Q history_process_decoded_internal_txs_for_safe_task

  celery_worker_history_check_reorgs_task:
    <<: *scheduler
    command: celery -A safe_transaction_service.taskapp.celery_app worker --loglevel INFO --pool=gevent --autoscale=120,80 -Q history_check_reorgs_task

  celery_worker_history_send_webhook_task:
    <<: *scheduler
    command: celery -A safe_transaction_service.taskapp.celery_app worker --loglevel INFO --pool=gevent --autoscale=120,80 -Q history_send_webhook_task

  celery_worker_history_index_contract_metadata:
    <<: *scheduler
    command: celery -A safe_transaction_service.taskapp.celery_app worker --loglevel INFO --pool=gevent --autoscale=120,80 -Q history_index_contract_metadata







