version: '2.2' # extends only support in 2.x


##########################################
# service
##########################################

# TODO: worker 里需要禁用所有 API 路由

services:

  #################### celery beat ##############################

  # celery worker：
  worker: &worker
    container_name: worker
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production_celery
    depends_on:
      - db
      - redis
    command: celery -A safe_transaction_service.taskapp worker --loglevel INFO --pool=gevent --autoscale=120,80
    # exec celery -A safe_transaction_service.taskapp worker --loglevel $log_level --pool=gevent --autoscale=120,80


  # celery beat：
  scheduler:
    <<: *worker
    container_name: scheduler
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production_celery
    command: celery -A safe_transaction_service.taskapp beat -S django_celery_beat.schedulers:DatabaseScheduler --loglevel INFO

    # celery -A safe_transaction_service.taskapp worker --loglevel $log_level --pool=gevent --autoscale=120,80
    # command: tini -- celery -A maneki.taskapp beat -l INFO
    # exec celery -A safe_transaction_service.taskapp beat -S django_celery_beat.schedulers:DatabaseScheduler --loglevel $log_level