version: '2.2' # extends only support in 2.x


##########################################
# celery worker
##########################################


services:

  #################### celery base ##############################

  # celery beat：
  scheduler: &scheduler
    container_name: worker
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production_celery
    depends_on:
      - db
      - redis
    command: celery -A safe_transaction_service.taskapp beat -S django_celery_beat.schedulers:DatabaseScheduler --loglevel INFO
    # command: celery -A safe_transaction_service.taskapp worker --loglevel INFO --pool=gevent --autoscale=120,80


  #################### celery worker group ##############################

  # celery worker：
  celery_worker_default:
    <<: *scheduler
    container_name: celery_worker_default
    command: celery -A safe_transaction_service.taskapp worker --loglevel INFO --pool=gevent --autoscale=120,80 -Q default

  celery_worker_history:
    <<: *scheduler
    container_name: celery_worker_history
    command: celery -A safe_transaction_service.taskapp worker --loglevel INFO --pool=gevent --autoscale=120,80 -Q history

  celery_worker_contracts:
    <<: *scheduler
    container_name: celery_worker_contracts
    command: celery -A safe_transaction_service.taskapp worker --loglevel INFO --pool=gevent --autoscale=120,80 -Q contracts

  celery_worker_notifications:
    <<: *scheduler
    container_name: celery_worker_notifications
    command: celery -A safe_transaction_service.taskapp worker --loglevel INFO --pool=gevent --autoscale=120,80 -Q notifications

  celery_worker_tokens:
    <<: *scheduler
    container_name: celery_worker_tokens
    command: celery -A safe_transaction_service.taskapp worker --loglevel INFO --pool=gevent --autoscale=120,80 -Q tokens
