version: '2.2' # extends only support in 2.x


##########################################
# service
##########################################

services:

  #################### api service: transactions ##############################
  api_tx1: &api_tx1
    extends:
      file: compose-prod-base.yml
      service: server
    environment:
      - USE_DOCKER=yes
      - API_USE_MICRO_SERVICE=1
      - API_MICRO_SERVICE_NAME=transactions

  api_tx2:
    <<: *api_tx1

  api_tx3:
    <<: *api_tx1

  api_tx4:
    <<: *api_tx1

