version: '3.5'

# 自定义数据卷:
volumes:
  nginx-shared:
  postgres_data:


######################################################


services:
  nginx:
    image: nginx:alpine
    hostname: nginx
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-shared:/nginx
    depends_on:
      - web

  redis:
    image: redis:alpine
    container_name: redis2
    ports:
      - "6379:6379"

  db:
    image: postgres:10-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    container_name: web
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - redis
    working_dir: /app
    ports:
      - "8888:8888"
    volumes:
      - nginx-shared:/nginx
    command: docker/web/run_web.sh

  worker: &worker
    container_name: worker
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: docker/web/celery/worker/run.sh


  scheduler:
    <<: *worker
    container_name: scheduler
    command: docker/web/celery/scheduler/run.sh



#  ganache:
#    image: trufflesuite/ganache-cli:latest
#    command: -d --defaultBalanceEther 10000 -a 10 --noVMErrorsOnRPCResponse --gasLimit 10000000 --host 0.0.0.0 --chainId 1337
#    ports:
#      - "8545:8545"
